name: hunyuan_sam3d
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.7.15
  - ld_impl_linux-64=2.40
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - ncurses=6.5
  - openssl=1.1.1w
  - pip=25.1
  - pthread-stubs=0.3
  - python=3.10.0
  - readline=8.3
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tk=8.6.14
  - tzdata=2025b
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu121
      - --find-links https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-2.5.1_cu121.html
      - aiohttp==3.13.2
      - astor==0.8.1
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - cos-python-sdk-v5==1.9.38
      - crcmod==1.7
      - cython==3.2.1
      - decord==0.6.0
      - easydict==1.13
      - einops==0.8.1
      - fastapi
      - ftfy==6.1.1
      - gradio==5.49.0
      - gsplat==1.5.3
      - hydra-core==1.3.2
      - huggingface-hub==1.22.0
      - idna==3.10
      - igraph==0.11.8
      - imageio==2.37.2
      - iopath==0.1.10
      - kaolin==0.17.0
      - lightning==2.5.6
      - loguru==0.7.2
      - numpy==1.26.4
      - nvidia-cuda-nvcc-cu12==12.8.93
      - omegaconf==2.3.0
      - open3d==0.18.0
      - opencv-python==4.9.0.80
      - optree==0.14.1
      - pillow==11.3.0
      - plyfile==1.1.3
      - psutil==7.0.0
      - pycocotools==2.0.7
      - pycryptodome==3.23.0
      - pymeshfix==0.17.0
      - pyyaml>=6.0
      - regex==2024.11.6
      - requests==2.32.4
      - seaborn==0.13.2
      - six==1.17.0
      - spconv-cu120==2.3.6
      - tencentcloud-sdk-python==3.0.1462
      - tencentcloud-sdk-python-ai3d==3.0.1424
      - tencentcloud-sdk-python-common==3.0.1443
      - timm==1.0.17
      - torch==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - trimesh==4.9.0
      - typing-extensions==4.12.2
      - urllib3==2.5.0
      - uvicorn
      - utils3d @ git+https://github.com/EasternJournalist/utils3d.git@3913c65d81e05e47b9f367250cf8c0f7462a0900
      - warp-lang==1.15.0
      - xatlas==0.0.9
      - xmltodict==0.14.2
