name: hunyuan
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.7.15
  - ld_impl_linux-64=2.40
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - ncurses=6.5
  - openssl=1.1.1w
  - pip=25.1
  - pthread-stubs=0.3
  - python=3.10.0
  - readline=8.3
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tk=8.6.14
  - tzdata=2025b
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - cos-python-sdk-v5==1.9.38
      - crcmod==1.7
      - fastapi
      - idna==3.10
      - numpy==2.2.6
      - pycryptodome==3.23.0
      - pyyaml>=6.0
      - requests==2.32.4
      - six==1.17.0
      - tencentcloud-sdk-python==3.0.1462
      - tencentcloud-sdk-python-ai3d==3.0.1424
      - tencentcloud-sdk-python-common==3.0.1443
      - trimesh==4.7.4
      - urllib3==2.5.0
      - uvicorn
      - xmltodict==0.14.2
