"""Stable constants shared by exact-cover policy and render validation."""

from __future__ import annotations


POLICY_REPORT_SCHEMA_VERSION = "qwen-policy-exact-cover-report/v1"
POLICY_PLAN_MODE = "explicit_best_effort_policy_exact_cover"
POLICY_INPUT_SCHEMA_VERSION = "qwen-policy-exact-cover/v1"

APPLICABLE_ASSIGNMENT_STATUSES = {"auto", "approved"}
POLICY_FALLBACK_STATUS = "policy_fallback"
POLICY_FALLBACK_CONFIDENCE_BASIS = "policy fallback; not evidence confidence"

SOURCE_VISUAL_PRESERVE_ACTION = "source_visual_preserve"
CORROBORATED_SOURCE_MDL_TIER = "corroborated_source_visual_nvidia_mdl"
SOURCE_CORROBORATION_REASON_CODES = {
    "REFERENCE_PALETTE_MULTIVIEW_COLOR_CORROBORATION",
    "RARE_SOURCE_VISUAL_SIGNATURE",
    "REPEATED_GEOMETRY_SOURCE_LOCATOR",
}
SOURCE_MDL_REPLACEMENT_REASON_CODES = SOURCE_CORROBORATION_REASON_CODES | {
    "SOURCE_VISUAL_SIGNATURE_REPLACED_BY_NVIDIA_MDL",
}
SOURCE_MDL_CONFIRMED_REASON_CODE = "QWEN_CONFIRMED_NVIDIA_MDL_SELECTION"
SOURCE_MDL_PROVISIONAL_REASON_CODES = {
    "QWEN_HIGH_CONFIDENCE_NVIDIA_MDL_CANDIDATE",
    "QA_POST_RENDER_VALIDATION_REQUIRED",
}
CORROBORATED_SOURCE_PROVISIONAL_MATERIAL_BASIS = (
    "high_confidence_whitelist_candidate_pending_render_qa"
)
CORROBORATED_SOURCE_MIN_PROVISIONAL_CONFIDENCE = 0.85
SOURCE_ACCENT_CHROMATIC_COLORS = {
    "red",
    "orange",
    "yellow",
    "green",
    "blue",
    "pink",
}
SOURCE_ACCENT_MAX_REGISTRY_FRACTION = 0.05
SOURCE_ACCENT_MIN_SIGNATURE_COUNT = 4
SOURCE_ACCENT_MIN_GEOMETRY_REPEAT_COUNT = 4
SOURCE_ACCENT_MIN_SATURATION = 0.5
SOURCE_ACCENT_MIN_OPACITY = 0.99
NEUTRAL_FALLBACK_TIERS = {
    "neutral_default",
    "source_preserve_unavailable_neutral_fallback",
    "source_visual_preserve",
}


__all__ = [
    "APPLICABLE_ASSIGNMENT_STATUSES",
    "CORROBORATED_SOURCE_MDL_TIER",
    "CORROBORATED_SOURCE_MIN_PROVISIONAL_CONFIDENCE",
    "CORROBORATED_SOURCE_PROVISIONAL_MATERIAL_BASIS",
    "NEUTRAL_FALLBACK_TIERS",
    "POLICY_FALLBACK_CONFIDENCE_BASIS",
    "POLICY_FALLBACK_STATUS",
    "POLICY_INPUT_SCHEMA_VERSION",
    "POLICY_PLAN_MODE",
    "POLICY_REPORT_SCHEMA_VERSION",
    "SOURCE_ACCENT_CHROMATIC_COLORS",
    "SOURCE_ACCENT_MAX_REGISTRY_FRACTION",
    "SOURCE_ACCENT_MIN_GEOMETRY_REPEAT_COUNT",
    "SOURCE_ACCENT_MIN_OPACITY",
    "SOURCE_ACCENT_MIN_SATURATION",
    "SOURCE_ACCENT_MIN_SIGNATURE_COUNT",
    "SOURCE_CORROBORATION_REASON_CODES",
    "SOURCE_MDL_CONFIRMED_REASON_CODE",
    "SOURCE_MDL_PROVISIONAL_REASON_CODES",
    "SOURCE_MDL_REPLACEMENT_REASON_CODES",
    "SOURCE_VISUAL_PRESERVE_ACTION",
]
